# Generated by Django 3.1.5 on 2021-02-15 01:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('failed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpage',
            name='fail',
            field=wagtail.core.fields.StreamField(
                [
                    ('paragraph', wagtail.core.blocks.RichTextBlock()),
                    ('image', wagtail.images.blocks.ImageChooserBlock()),
                    ('example_code', wagtail.core.blocks.StructBlock(
                        [
                            ('language', wagtail.core.blocks.ChoiceBlock(
                                blank=False,
                                choices=[
                                    ('cpp', 'C++'),
                                    ('java', 'Java'),
                                    ('python3', 'Python 3'),
                                    ('bash', 'Bash/Shell'),
                                    ('javascript', 'Javascript'),
                                    ('css', 'CSS'),
                                    ('html', 'HTML'),
                                    ('nginx', 'Nginx configuration file'),
                                    ('jinja', 'Jinja'),
                                    ('docker', 'Docker'),
                                    ('yaml', 'YAML'),
                                    ('json', 'JSON')],
                                null=False)),
                            ('code', wagtail.core.blocks.TextBlock()),
                            ('source', wagtail.core.blocks.URLBlock(
                                required=False))
                        ]
                    ))
                ]
            ),
        ),
    ]
