# Generated by Django 2.2.9 on 2019-12-22 22:37

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('name', models.CharField(unique=True, max_length=250)),
                ('intro', wagtail.core.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
