# Generated by Django 3.1.5 on 2021-01-23 22:37

from django.db import migrations, models
from django.template.defaultfilters import slugify


def migrate_category_slug(apps, schema_editor):
    Category = apps.get_model("categories", "Category")
    for category in Category.objects.all():
        category.slug = slugify(category.name)
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_category_slug),
    ]
